#site settings
title: imgraft
email: ag+imgraft@glaciology.net
description: An image georectification and feature tracking toolbox for MATLAB
baseurl: /imgraft
url: http://grinsted.github.io
twitter_username: agrinsted
github_username: grinsted
permalink: /:collection/:title/
theme: jekyll-theme-dinky
collections:
  faq:
    output: true
    permalink: /:collection/:name
  demo:
    output: true
    permalink: /:collection/:name